// Centralized copy for emotional, motivational messaging
export const COPY = {
  onboarding: {
    welcome: "Challenge me",
    subtitle: "Small challenges. Big shifts.",
    pickAreas: "What areas do you want to focus on?",
    pickCadence: "How often do you want a challenge?",
    pickWindow: "When should we nudge you?",
    socialToggle: "Share your journey with friends?",
    cta: "Challenge me",
    needThreeAreas: "Pick at least 3 areas to get started",
  },
  home: {
    firstSpark: "Your first challenge",
    nextSpark: "Next challenge",
    todaySpark: "Today's Challenge",
    startExplainer: "Once you press START, your challenge begins. Focus on the task and enjoy the moment!",
    swap: "Swap",
    swapUsed: "Swap used",
    start: "START",
    completed: "COMPLETED",
    giveUp: "I GIVE UP",
    later: "Later",
    breathe: "Take 3 deep breaths",
    howWasIt: "How was it?",
    wouldYouRepeat: "Would you do this again?",
    expired: "This challenge expired. Tomorrow's a new day.",
  },
  progress: {
    title: "Progress",
    streak: "day streak",
    topMoments: "Top Moments",
    byArea: "By Area",
    noMomentsYet: "Complete your first challenge to see it here",
  },
  social: {
    title: "Social",
    leaderboard: "Leaderboard",
    nudge: "Nudge",
    invite: "Invite friend",
    noFriendsYet: "Invite friends to compete and motivate each other",
  },
  settings: {
    title: "Settings",
    areas: "Your areas",
    cadence: "Cadence",
    window: "Notification window",
    socialOptIn: "Share with friends",
    dangerZone: "Danger Zone",
    resetAll: "Reset all data",
    resetConfirm: "Are you sure? This will delete your streak and all progress.",
  },
  notifications: {
    dailyTitle: "Your challenge is ready",
    dailyBody: "Time to start something new today",
    gentleNudgeTitle: "Still time for today's challenge",
    gentleNudgeBody: "Your challenge is waiting. Just 20 minutes to make a difference.",
    streakAtRiskTitle: "Don't break your streak!",
    streakAtRiskBody: "You've come so far. Complete today's challenge before midnight.",
  },
};
